(function(){'use strict';
function clean(x){return String(x==null?'':x).trim()}
function unknown(x){const s=clean(x);return !s||s.includes('不确定')||s.includes('不知道')}
function ageBand(x){x=clean(x).replace(/\s/g,'');if(x.includes('还没有'))return'None';if(x.includes('不到6个月'))return'<6m';if(x.includes('6–11')||x.includes('6-11'))return'6–11m';if(x.includes('1–2')||x.includes('1-2'))return'1–2y';if(x.includes('2年以上'))return'2y+';return'Unknown'}
function scoreBand(x){x=clean(x).replace(/\s/g,'');if(x==='740+')return'740+';if(x.includes('700–739')||x.includes('700-739'))return'700–739';if(x.includes('670–699')||x.includes('670-699'))return'670–699';if(x.includes('670以下'))return'<670';return'Unknown'}
function sev(x){x=clean(x).replace(/\s/g,'');if(unknown(x))return null;if(['0张','1张','0次','1次','0','1'].includes(x))return 0;if(x.includes('2–3')||x.includes('2-3'))return 1;if(x.includes('4–5')||x.includes('4-5'))return 2;if(x.includes('6张以上')||x.includes('6次以上')||x==='6+')return 3;return null}
function activity(a3,a4){const x=sev(a3),y=sev(a4);if(x==null||y==null)return'UNKNOWN';return ['LOW','MEDIUM','HIGH','VERY_HIGH'][Math.max(x,y)]}
function downBase(r,n){if(r==='INSUFFICIENT_DATA')return r;const o=['HIGH','MEDIUM','HIGH_RISK'];const i=o.indexOf(r);return i<0?r:o[Math.min(2,i+n)]}
function pred(p,f){if(!p||p.op==='ALWAYS')return true;const v=f[p.fact];switch(p.op){case'EQ':return v===p.value;case'IN':return p.values.includes(v);case'AND':return(p.args||[]).every(x=>pred(x,f));case'OR':return(p.args||[]).some(x=>pred(x,f));case'NOT':return!pred(p.arg,f);default:throw Error('Unsupported approval predicate: '+p.op)}}
function applyEffect(base,e){if(e.op==='CAP_AT')return e.value;if(e.op==='DOWNGRADE')return downBase(base,Number(e.steps||0));throw Error('Unsupported approval effect: '+e.op)}
function evaluate({cardKey,issuerCode,answers,config}){const ab=ageBand(answers.a1),sb=scoreBand(answers.a2),a3s=sev(answers.a3),a4s=sev(answers.a4),sig=activity(answers.a3,answers.a4);let base=(config.base_matrix[ab]||config.base_matrix.Unknown)[sb]||'INSUFFICIENT_DATA';const sens=config.issuer_sensitivity[issuerCode]||'MEDIUM';const ga=(config.activity_adjustment[sig]||{})[sens]||0;if(sig==='UNKNOWN'&&base!=='HIGH_RISK')base='INSUFFICIENT_DATA';else base=downBase(base,ga);const rc=[],ageCode=config.reason_code_maps.age[ab],scoreCode=config.reason_code_maps.score[sb];if(ageCode)rc.push(ageCode);if(scoreCode)rc.push(scoreCode);if(sig!=='UNKNOWN')rc.push('ACTIVITY_'+sig);const facts={credit_age_band:ab,credit_score_band:sb,approved_cards_12m_severity:a3s,applications_6m_severity:a4s,activity_signal:sig};for(const ov of (config.product_overlays||{})[cardKey]||[]){if(pred(ov.when,facts)){base=applyEffect(base,ov.effect);rc.push(ov.reason_code)}}return{baseApproval:base,activitySignal:sig,genericAdjustment:ga,reasonCodes:[...new Set(rc)]}}
window.ApprovalEngineV2={evaluate,ageBand,scoreBand,activity,pred,version:'approval-engine-2'};
})();
